<?php

class ProcessUserExtended extends ProcessUser {

  static public function getModuleInfo() {
		return array(
			'title' => __('Users extended', __FILE__), // getModuleInfo title
			'version' => 100, 
			'summary' => __('Extended view for user management', __FILE__), // getModuleInfo summary
			'permanent' => false, 
			'permission' => 'user-admin',
			); 
	}

	public function ___execute() {
	
		$out = '';

		$wrapper = new InputfieldWrapper;
		
		
		$fields = $this->modules->get("InputfieldFieldset");
		
		
		$form = $this->modules->get("InputfieldForm");
		$form->attr('method', 'get');
		$form->attr('id', 'userSearch');
		$form->label = $this->_("Filter users");
		if (!$this->input->get->roles && !$this->input->get->search) {
			$form->collapsed = Inputfield::collapsedYes;
		}
		
		
		$field = $this->modules->get("InputfieldText");
		$field->attr('name', 'search');
		$field->label = $this->_("Search");
		if ($this->input->get->search) {
			$this->input->whitelist('search', $this->input->get->search);
			$field->attr('value', htmlentities($this->input->get->search, ENT_QUOTES, 'UTF-8'));
		}
		
		$form->add($field);
		
		$field = $this->modules->get("InputfieldCheckboxes");
		$field->attr('name', 'roles');
		$field->optionColumns = 5;
		foreach(wire('roles') as $role) {
			if ($role->name == "guest") continue;
			$attrs = array();
			$this->input->whitelist("roles", $this->input->get->roles);
			if (is_array($this->input->get->roles)) {
				if(in_array($role->name, $this->input->get->roles)) {
					$attrs['selected'] = 'selected';
					
				}
			}
			$field->addOption($role->name, $role->get('title|name'), $attrs);
		}
		$field->label = $this->_("Filter by role");
		
		
		$form->add($field);
		
		$field = $this->modules->get("InputfieldSubmit");
		$field->attr('value', $this->_("Search"));
		$form->add($field);
		
		$fields->add($form);
		
		$out .= $fields->render();
		
		$selector = "limit=25, status<" . Page::statusMax;
		
		
		if ($this->input->get->roles) {
			$roles = new PageArray;
			foreach($this->input->get->roles as $roleName) {
				$roles->add($this->roles->get($roleName));
			}
			if ($role->id) $selector .= ", roles=$roles";
		}
		if ($this->input->get->search) {
			$fieldNames = implode("|", array_diff($this->showFields, array('name', 'created', 'modified', 'roles')));
			$search = $this->sanitizer->selectorValue($this->input->get->search);
			$directHit = $this->pages->get("name=$search");
			if ($directHit->id) $out .= "<h3>". $this->_('Found by username') .": <a href='./edit/?id=$directHit->id'>$directHit->name</a></h3>";
			$selector .= ", $fieldNames^=$search";
		}
		
		return $out . $this->renderList($selector, array("arrayToCSV" => false));
		
	}
	
	public function ___executeList() {
		return $this->renderList("limit=25, status<" . Page::statusMax); 
	}
	
	protected function renderList($selector, $pagerOptions = null) {
		$out = '';

		if(!$this->pages->getTemplate()) {
			$form = $this->getTemplateFilterForm();		
			$out = $form->render();
		}

		$table = $this->modules->get("MarkupAdminDataTable"); 
		$table->setEncodeEntities(false); 
		$fieldNames = $this->showFields; 
		$fieldLabels = $fieldNames; 

		foreach($fieldLabels as $key => $name) {
			if($name == 'name') {
				$fieldLabels[$key] = $this->_('Name'); // Label for 'name' field
				continue; 
			}
			$field = wire('fields')->get($name); 	
			$languageID = wire('user')->language ? wire('user')->language->id : '';
			$label = $field->get('label' . $languageID);
			if(!$label) $label = $field->label; 
			if(!$label) $label = $name; 
			$fieldLabels[$key] = htmlentities($label, ENT_QUOTES, "UTF-8");
		}

		$table->headerRow($fieldLabels); 
		$pages = $this->pages->find($selector); 

		foreach($pages as $page) {
			if(!$page->editable()) continue; 
			$n = 0; 
			$row = array();
			foreach($fieldNames as $name) {
				if(!$n) $row[$page->get($name) . ' '] = "edit/?id={$page->id}";
					else $row[] = $this->renderListFieldValue($name, $page->get($name)); 
				$n++;
			}
			$table->row($row); 
		}

		if($this->page->addable()) $table->action(array($this->_('Add New') => 'add/'));

		if($pages->getTotal() > count($pages)) {
			$pager = $this->modules->get("MarkupPagerNav"); 
			$out .= $pager->render($pages, $pagerOptions);
		}

		$out .= $table->render();

		return $out; 
	}
}
